{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a093ed4b-6a2e-4a49-a142-adaa7c51421a",
   "metadata": {},
   "outputs": [],
   "source": [
    "'''\n",
    "Sets up json folders for clustering based on edit-distance similarity. \n",
    "To run, cd to data directory and run command \"python ../dsci_550_a1/editDistanceClusterWorkflow.py\"\n",
    "'''\n",
    "\n",
    "# System Path #\n",
    "import os\n",
    "import sys \n",
    "import shutil\n",
    "import subprocess\n",
    "import pandas as pd\n",
    "import subprocess\n",
    "import time\n",
    "import json\n",
    "\n",
    "##############################################################################################################################\n",
    "\n",
    "## Making Directories ##\n",
    "\n",
    "## Check cwd. if not in project director, prompt user##\n",
    "starting_dir = os.getcwd()\n",
    "\n",
    "if not starting_dir.endswith(\"dsci_550_a1\"):\n",
    "    x = input(\"This script has relative paths from the project directory. Are you sure you want to continue? (y/n):\")\n",
    "    if x.strip().lower() == \"y\":\n",
    "        pass\n",
    "    else:\n",
    "        sys.exit(\"Script exited\")\n",
    "\n",
    "## Create clustering output directory ##\n",
    "if not os.path.exists(\"./clustering\"):\n",
    "    os.makedirs(\"./clustering\")\n",
    "\n",
    "if not os.path.exists(\"./clustering/editdistance\"):\n",
    "    os.makedirs(\"./clustering/editdistance\")\n",
    "\n",
    "\n",
    "## Create directories for aggregate.json, json, and conf files in data folder ##\n",
    "\n",
    "parent_dir = \"./data/tika_similarity\"\n",
    "child_dirs = [\"aggregate_json\", \"conf\", \"json\", \"temp\", \"clusters\"]\n",
    "\n",
    "os.makedirs(parent_dir, exist_ok = True)\n",
    "for child in child_dirs:\n",
    "    os.makedirs(os.path.join(parent_dir, child), exist_ok = True)\n",
    "\n",
    "##############################################################################################################################\n",
    "\n",
    "## User input ##\n",
    "# user inputs fields to cluster by and number of files they wish to cluster\n",
    "\n",
    "outfile = \"./data/processed/haunted_places_features_added.tab\"\n",
    "columns = pd.read_csv(outfile, nrows = 0, sep = \"\\t\").columns.tolist()\n",
    "\n",
    "## Subset of files you want to cluster ##\n",
    "num_files = '' \n",
    "while not num_files.isdigit() or not (0 < int(num_files) <= 10992):\n",
    "    num_files = input(\"Enter number of haunted places to cluster: \")\n",
    "\n",
    "num_files = num_files\n",
    "\n",
    "## Subset of fields you want to consider ##\n",
    "fields = ''\n",
    "while True:\n",
    "    fields = input(\"Enter a list of fields to keep (e.g., '[\\\"name\\\", \\\"age\\\"]'): \").strip()\n",
    "\n",
    "    try:\n",
    "        fields_check = json.loads(fields)\n",
    "        if isinstance(fields_check, list):\n",
    "            if all([(field in columns) for field in json.loads(fields)]):\n",
    "                break\n",
    "            else:\n",
    "                print(\"Some of the fields you entered are not in {outfile}. Please try again.\")\n",
    "        else:\n",
    "            print(\"Incorrect format. Please use json list (e.g., '[\\\"name\\\", \\\"age\\\"]')\")\n",
    "    except json.JSONDecodeError:\n",
    "        print(\"Incorrect format. Please use json list (e.g., '[\\\"name\\\", \\\"age\\\"]')\")\n",
    "\n",
    "##############################################################################################################################\n",
    "\n",
    "## Check if json files are unpacked. ##\n",
    "# If not, unpack using tsvtojson and repackage.py\n",
    "\n",
    "json_dir = os.path.join(parent_dir, \"json\")\n",
    "\n",
    "if os.path.isdir(json_dir) and any(f.endswith(\".json\") for f in os.listdir(json_dir)):\n",
    "    json_count = sum(1 for f in os.listdir(json_dir) if f.endswith(\".json\"))\n",
    "    print(\"\\n\" + \"-\"*50, \"You have already unpacked the haunted place json files\", f\"Total Json count: {json_count}\", \"Skipping unpacking using 'tsvtojson' and 'repackage.py'.\", sep = \"\\n\", end = \"\\n\" + \"-\"*50)\n",
    "else:\n",
    "    ##############################################################################################################################\n",
    "    ## Run tsvtojson and repackage ##\n",
    "    print(\"\\n\" + \"-\"*50, \"Unpacking haunted places dataset using 'tsvtojson' and 'repackage.py'\", \"Jsons stored in ./data/tika_similarity/json/*\", \"Aggregate_json stored in ./data/tika_similarity/aggregate_json/aggregate.json\", sep = \"\\n\", end = \"\\n\" + \"-\"*50)\n",
    "    \n",
    "    ## Read CSV and save copy with no header for tsvtojson ##\n",
    "    df = pd.read_csv(outfile, sep=\"\\t\")  \n",
    "    df.to_csv(outfile.replace(\"added\", \"added_nh\"), index = False, header = False, sep = \"\\t\")\n",
    "\n",
    "    ## column_headers.conf ##\n",
    "    with open(\"./data/tika_similarity/conf/col_headers.conf\", \"w\") as f:\n",
    "        f.write(\"\\n\".join(df.columns.tolist()))\n",
    "        f.close()\n",
    "\n",
    "    ## encoding.conf ##\n",
    "    supported_text_encodings = ['utf-8', 'us-asci'] \n",
    "    with open(\"./data/tika_similarity/conf/encoding.conf\", \"w\") as f:\n",
    "        f.write(\"\\n\".join(supported_text_encodings))\n",
    "        f.close()\n",
    "\n",
    "    ##############################################################################################################################\n",
    "\n",
    "    ## Run tsvtojson ##\n",
    "    command = [\n",
    "        \"tsvtojson\",\n",
    "        \"-t\", outfile.replace(\"added\", \"added_nh\"),\n",
    "        \"-j\", \"./data/tika_similarity/aggregate_json/aggregate.json\",\n",
    "        \"-c\", \"./data/tika_similarity/conf/col_headers.conf\",\n",
    "        \"-o\", \"hauntedPlaces\",\n",
    "        \"-e\", \"./data/tika_similarity/conf/encoding.conf\",\n",
    "        \"-s\", \"0.8\",\n",
    "        \"-v\"\n",
    "    ]\n",
    "\n",
    "    result = subprocess.run(command, capture_output=True, text=True)\n",
    "\n",
    "    print(\"STDOUT:\", result.stdout)\n",
    "    print(\"STDERR:\", result.stderr)\n",
    "\n",
    "    # Remove temporary dataframe with no headers\n",
    "    os.remove(outfile.replace(\"added\", \"added_nh\"))\n",
    "\n",
    "    ##############################################################################################################################\n",
    "\n",
    "    ## Run repackage ##\n",
    "    # Move to json directory #\n",
    "    json_dir = \"./data/tika_similarity/json\"\n",
    "    os.chdir(json_dir)\n",
    "\n",
    "    # Run command #\n",
    "    command = [\n",
    "        \"repackage\",\n",
    "        \"-j\", \"../aggregate_json/aggregate.json\",\n",
    "        \"-o\", \"hauntedPlaces\", \"-v\"\n",
    "    ]\n",
    "\n",
    "    result = subprocess.run(command, capture_output=True, text=True)\n",
    "    print(\"STDOUT:\", result.stdout)\n",
    "    print(\"STDERR:\", result.stderr)\n",
    "\n",
    "    print(\"Jsons stored in './data/tika_similarity/json' and are ready for clustering\")\n",
    "\n",
    "##############################################################################################################################\n",
    "\n",
    "## Run editdistanceSimilarity.py to get editdistance.csv ##\n",
    "print(\"\\nNow running ./dsci_550_a1/runEditDistanceSimilarity.py:\", end = \"\\n\\n\")\n",
    "## Move back into project directory ##\n",
    "os.chdir(starting_dir)\n",
    "\n",
    "command = [\n",
    "    \"python\", \"./dsci_550_a1/runEditDistanceSimilarity.py\",\n",
    "    \"--input_dir\", \"./data/tika_similarity/json\",\n",
    "    \"--subset_dir\", \"./data/tika_similarity/temp\",\n",
    "    \"--num_files\", num_files, \n",
    "    \"--out_csv\", \"./clustering/editdistance/editdistance.csv\",\n",
    "    \"--fields\", fields\n",
    "]\n",
    "\n",
    "result = subprocess.run(command, capture_output=True, text=True)\n",
    "print(\"STDOUT:\", result.stdout)\n",
    "print(\"STDERR:\", result.stderr)\n",
    "\n",
    "# Replace '/temp/' with '/json/' in editdistance.csv #\n",
    "df2 = pd.read_csv(\"./clustering/editdistance/editdistance.csv\", sep = \",\")\n",
    "df2['x-coordinate'] = df2['x-coordinate'].apply(lambda x: x.replace(\"/temp/\", \"/json/\"))\n",
    "df2['y-coordinate'] = df2['y-coordinate'].apply(lambda x: x.replace(\"/temp/\", \"/json/\"))\n",
    "df2.to_csv(\"./clustering/editdistance/editdistance.csv\", sep = \",\", index = False)\n",
    "\n",
    "##############################################################################################################################\n",
    "\n",
    "## Run 'edit-cosine-circle-packing.py' 'edit-cosine-cluster.py' and 'generateLevelCluster.py' ##\n",
    "\n",
    "command = [\n",
    "    \"python\", \"./clones/tika-img-similarity/tikasimilarity/cluster/edit-cosine-circle-packing.py\",\n",
    "    \"--inputCSV\", \"./clustering/editdistance/editdistance.csv\",\n",
    "    \"--cluster\", \"2\",\n",
    "]\n",
    "\n",
    "result = subprocess.run(command, capture_output=True, text=True)\n",
    "print(\"STDOUT:\", result.stdout)\n",
    "print(\"STDERR:\", result.stderr)\n",
    "\n",
    "\n",
    "command = [\n",
    "    \"python\", \"./clones/tika-img-similarity/tikasimilarity/cluster/edit-cosine-cluster.py\",\n",
    "    \"--inputCSV\", \"./clustering/editdistance/editdistance.csv\",\n",
    "    \"--cluster\", \"2\",\n",
    "]\n",
    "\n",
    "result = subprocess.run(command, capture_output=True, text=True)\n",
    "print(\"STDOUT:\", result.stdout)\n",
    "print(\"STDERR:\", result.stderr)\n",
    "\n",
    "command = [\n",
    "    \"python\", \"./clones/tika-img-similarity/tikasimilarity/cluster/generateLevelCluster.py\",\n",
    "]\n",
    "\n",
    "result = subprocess.run(command, capture_output=True, text=True)\n",
    "print(\"STDOUT:\", result.stdout)\n",
    "print(\"STDERR:\", result.stderr)\n",
    "\n",
    "##############################################################################################################################\n",
    "\n",
    "## Make HTML ##\n",
    "command = \"cp -R ./clones/etllib/html/* .\"\n",
    "\n",
    "result = subprocess.run(command, shell = True, capture_output=True, text=True)\n",
    "\n",
    "print(\"STDOUT:\", result.stdout)\n",
    "print(\"STDERR:\", result.stderr)\n",
    "\n",
    "##############################################################################################################################\n",
    "## Save Metadata and move outputs ##\n",
    "\n",
    "print(\"\\n\" + \"-\"*50, \"Metadata saved to ./clustering/editdistance/metadata.json\", sep = \"\\n\", end = \"\\n\\n\")\n",
    "\n",
    "metadata = {\n",
    "    \"num_files\" : num_files,\n",
    "    \"fields\" : fields,\n",
    "    \"input_data\" : outfile\n",
    "}\n",
    "\n",
    "with open(\"./clustering/editdistance/metadata.json\", \"w\") as f:\n",
    "    json.dump(metadata, f, indent = 4)\n",
    "\n",
    "print(\"Moving output files to ./clustering/editdistance/visualization\", end = \"\\n\\n\")\n",
    "\n",
    "output_dir = \"./clustering/editdistance\"\n",
    "output_html = ['./circlepacking.html', 'cluster-d3.html', 'levelCluster-d3.html']\n",
    "output_json = ['circle.json', 'levelCluster.json', 'clusters.json']\n",
    "\n",
    "output_viz = os.path.join(output_dir, \"visualization\")\n",
    "os.makedirs(os.path.join(output_viz), exist_ok = True)\n",
    "\n",
    "for file in output_html:\n",
    "    dest_path = os.path.join(output_viz,os.path.basename(file))\n",
    "    shutil.move(file, dest_path)\n",
    "\n",
    "for file in output_json:\n",
    "    dest_path = os.path.join(output_viz,os.path.basename(file))\n",
    "    shutil.move(file, dest_path)\n",
    "    \n",
    "print(\"All Done :)\", \"\\n\" + \"-\"*50, sep = \"\\n\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
